services:

  voting-bot:
      build: ./bot
      restart: unless-stopped
      environment:
        - MM_URL=mattermost
        - MM_TOKEN=${MM_BOT_TOKEN}
        - TARANTOOL_HOST=tarantool
      depends_on:
        - mattermost
        - tarantool
      volumes:
        - ./bot:/app
  
  mattermost:
    image: mattermost/mattermost-team-edition
    ports:
      - "8065:8065"
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@postgres:5432/mattermost?sslmode=disable&connect_timeout=10
    depends_on:
      - postgres
    volumes:
      - ./mattermost/config:/mattermost/config
      - ./mattermost/data:/mattermost/data
      - ./mattermost/logs:/mattermost/logs
      - ./mattermost/plugins:/mattermost/plugins
      - ./mattermost/client-plugins:/mattermost/client/plugins

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  tarantool:
    image: tarantool/tarantool:2
    ports:
      - "3301:3301"
    volumes:
      - ./tarantool:/var/lib/tarantool
      - ./tarantool-init.lua:/opt/tarantool/init.lua
    command: tarantool /opt/tarantool/init.lua